name: Integration tests

on:
  pull_request:
  push:
  schedule:
    # Run Monday morning at 3 o'clock
    #       ┌───────────── minute (0 - 59)
    #       │ ┌───────────── hour (0 - 23)
    #       │ │ ┌───────────── day of the month (1 - 31)
    #       │ │ │ ┌───────────── month (1 - 12)
    #       │ │ │ │ ┌───────────── day of the week (0 - 6)
    #       │ │ │ │ │
    #       │ │ │ │ │
    #       │ │ │ │ │
    - cron: 0 3 * * 1
  workflow_dispatch:

jobs:
  integration:
    name: laravel
    runs-on: ubuntu-20.04
    env:
      COMPOSER_NO_INTERACTION: 1

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none

      # Due to version incompatibility with older Laravels we test, we remove it
      - run: composer remove --dev friendsofphp/php-cs-fixer --no-update
      - run: composer remove --dev nunomaduro/larastan --no-update
      - run: composer require illuminate/contracts:^8.0 --no-update

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - run: composer install --prefer-dist --no-suggest

      - run: tests/integration-laravel.sh
