name: Tests

on: [push, pull_request]

jobs:
  integration:
    strategy:
      matrix:
        php: [7.2, 7.3, 7.4]
        laravel: [^6.0, ^7.0]
        lazy_types: ['false', 'true']
    name: P=${{ matrix.php }} L=${{ matrix.laravel }} Lazy types=${{ matrix.lazy_types }}
    runs-on: ubuntu-18.04
    env:
      COMPOSER_NO_INTERACTION: 1

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      # Due to version incompatibility with older Laravels we test, we remove it
      - run: composer remove --dev matt-allan/laravel-code-style --no-update
      - run: composer require illuminate/contracts:${{ matrix.laravel }} --no-update
      - run: composer remove --dev nunomaduro/larastan --no-update

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.php }}-${{ matrix.laravel }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-${{ matrix.php }}-${{ matrix.laravel }}-composer-

      - run: composer update --prefer-dist --no-progress

      - name: Enable lazy types conditionally
        run: echo "::set-env name=TESTS_ENABLE_LAZYLOAD_TYPES::1"
        if: matrix.lazy_types == 'true'

      - name: Run tests
        run: composer tests
